### PR TITLE
Add "initial graph" parameter to dependency resolver, to support incremental resolution

### LINKED ISSUE #45: Add support for upgrading only a selection of projects
Similar to recent [Carthage](https://github.com/Carthage/Carthage) features—if the end-user doesn't want to upgrade their whole dependency graph, they should be able to specify an existing dependency graph, and which projects to consider for upgrades.

### LINKED ISSUE #46: Add support for adding new projects into an existing graph
Similar to recent [Carthage](https://github.com/Carthage/Carthage) features, end-users may want to add new dependencies to a project which is otherwise fully resolved already, and in doing so, only work to resolve the added dependencies.

This is also similar to #45, but the behaviors are slightly different.

### PR DESCRIPTION
**Pull request by jspahrsummers**
Resolves #45. Resolves #46.

cc @mdiep

### CODE REVIEW

**Comment by mdiep** [comment]
I think you also need the full set of constraints (i.e., I don't think you have that here?). `carthage update A` may also update `B` if `B` is a dependency of `A`, so the resolver needs to know what versions are valid for `B`.

**Comment by jspahrsummers** [comment]
There are a few different scenarios supported here, and I didn't do a good enough job explaining them, so let me try now.

In all of them, assume that the user of Arbiter (e.g., Carthage) already has an `ArbiterResolvedDependencyGraph` from a previous run. The details of serializing and deserializing the graph are left up to the user (e.g., `Cartfile.resolved` format). The "full set of constraints" you mention are obtainable from `ArbiterResolvedDependencyGraphProjectRequirement()`, though maybe that API should be made easier. 

### Adding a new project to a resolved graph

_Roughly equivalent, I think, to `carthage add Project` followed by `carthage update Project`._

This is the most straightforward scenario: simply pass the existing `ArbiterResolvedDependencyGraph` to `ArbiterCreateResolver()`, then list _only_ the new project(s) you want to add in the `ArbiterDependencyList`. The dependency list captures the project identifiers and requirements of each.

When resolution has completed, projects' versions in the provided graph should be unchanged (but their constraints may have been tightened), and the new project and its transitive dependencies will have been added.

### Adding new requirements to a project in a resolved graph

_No Carthage equivalent?_

I'm not sure there's a concrete use case here—it just arose naturally from the design. Maybe this could be used as a way to union two resolved graphs?

Anyways, if you did want to do this, you'd pass the existing `ArbiterResolvedDependencyGraph` to `ArbiterCreateResolver()`, then list _existing projects in the graph_ in the `ArbiterDependencyList`. The requirements in the dependency list will be intersected with whatever the graph has, or resolution will fail if that's impossible.

### Upgrading one project in a resolved graph

_Equivalent to `carthage update Project`._

This one is the hardest to infer just from the API, but I've tried to capture it in the header documentation.

Basically, the usage will look something like this:

1. Deserialize the existing `ArbiterResolvedDependencyGraph`.
1. Collect the `ArbiterProjectIdentifier`s that _should not_ be upgraded. In the Carthage example, this would be the projects listed in the `Cartfile` which were not passed to `carthage update`.
1. Invoke `ArbiterResolvedDependencyGraphCopyWithNewRoots()` with the projects that _should not_ be upgraded. This will create a new sub-graph that includes only those projects and their transitive dependencies (i.e., reachable nodes from those roots, like Git revwalking).
1. Pass the resulting sub-graph to `ArbiterCreateResolver()`, with the projects which _should_ be upgraded as the `ArbiterDependencyList`. The dependency list contains the requirements for those projects when considering them for upgrades.

At the end of this process:

* The projects explicitly specified by the end user will have been upgraded if possible.
* The transitive dependencies of the projects explicitly specified will be upgraded _iff_ they are not used elsewhere in the graph.
* Other existing projects, and the transitive dependencies thereof, will be locked in place and not upgraded.

**Comment by jspahrsummers** [comment]
(some Travis lulz here—those build failures are spurious)

**Comment by mdiep** [comment]
Ah, okay. That makes a lot of sense. 👍🏻

That explanation would be a great addition to the documentation.

**Pull request merged**
